# Generated by Django 3.2.13 on 2022-10-28 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_alter_review_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.ManyToManyField(related_name='like_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
